# Generated by Django 2.0.7 on 2018-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessioninfo',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sessionkey', models.CharField(blank=True, max_length=30)),
                ('session', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=30, unique=True)),
                ('unfinishedorders', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('schoolid', models.CharField(blank=True, max_length=14)),
                ('telephone', models.CharField(blank=True, max_length=12)),
                ('dorm', models.CharField(blank=True, max_length=15)),
                ('gender', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
